# Generated by Django 2.1.3 on 2019-01-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_id', models.TextField()),
                ('bcc', models.TextField()),
                ('cc', models.TextField()),
                ('sub', models.TextField()),
                ('message', models.TextField()),
                ('csv', models.FileField(upload_to='files/')),
                ('mail_time', models.DateTimeField()),
            ],
        ),
    ]
